import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <header className="header">
            <div>
              <h1 style={{ fontSize: "24px", fontWeight: "bold" }}>
                Bookmark Manager
              </h1>
            </div>
            <div style={{ display: "flex", gap: "15px", alignContent: "center"}}>
              <SignedOut>
                <SignInButton>
                 <button className="btn btn-primary">Sign In</button>
                </SignInButton>
                <SignUpButton>
                  <button className="btn btn-primary">Sign Up</button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <main className="main">{children}</main>
        </body>
     </html>
    </ClerkProvider>
  );
}
